/**
  ******************************************************************************
  * @file    crypto.c
  * @author  MCD Application Team
  * @brief   NS CRYPTO program
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "com.h"
#include "cryp.h"
#include "psa/client.h"
#include "psa/crypto_values.h"
#include "crypto_tests_common.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
/* Private function prototypes -----------------------------------------------*/
/* Private functions ---------------------------------------------------------*/
void FW_APP_CRYPTO_PrintMenu(void);
static void DISPLAY_AEAD(void);

/**
  * @brief  Display the CRYPTO Menu choices on HyperTerminal
  * @param  None.
  * @retval None.
  */
void FW_APP_CRYPTO_PrintMenu(void)
{
  (void)printf("\r\n=================== Cryptography Menu ====================\r\n\n");
  (void)printf("  RNG -------------------------------------------------- 1\r\n\n");
#ifdef TFM_CRYPTO_TEST_ALG_GCM
  (void)printf("  AES GCM ---------------------------------------------- 2\r\n\n");
#endif /* GCM */
#ifdef TFM_CRYPTO_TEST_ALG_CBC
  (void)printf("  AES CBC ---------------------------------------------- 3\r\n\n");
#endif /* CBC */
#ifdef TFM_CRYPTO_TEST_ALG_CCM
  (void)printf("  AES CCM ---------------------------------------------- 4\r\n\n");
#endif /* CCM */
  (void)printf("  SHA224 ----------------------------------------------- 5\r\n\n");
  (void)printf("  SHA256 ----------------------------------------------- 6\r\n\n");
  (void)printf("  RSA 2048 --------------------------------------------- 7\r\n\n");
  (void)printf("  Previous menu ---------------------------------------- x\r\n\n");
  (void)printf("  Selection :\r\n\n");
  (void)printf("  ");
}

/**
  * @brief  Run the CRYPTO example
            In each test, the PSA API used are display
  * @param  None.
  * @retval None.
  */
void FW_APP_CRYPTO_Run(void)
{
  uint8_t key = 0U;
  uint8_t exit = 0U;

  struct test_result_t ret;

  psa_status_t psa_status;
  size_t size = 16U;
  uint8_t output[16] = {0};

  /* Print Menu message*/
  FW_APP_CRYPTO_PrintMenu();

  while (exit == 0U)
  {
    /* Clean the input path */
    (void)COM_Flush();

    /* Receive key */
    if (COM_Receive(&key, 1U, RX_TIMEOUT) == HAL_OK)
    {
      (void)printf("%c\r\n", key);
      switch (key)
      {
        case '1' :
          /* Display random generated by psa api */
          (void)printf("\nPSA API tested : \r\n\n");
          (void)printf("psa_generate_random() \r\n");
          psa_status = psa_generate_random(output, size);
          if (psa_status == PSA_SUCCESS)
          {
            (void)printf("\r\nTEST PASSED\r\n");
            (void)printf("\nRandom generated (size 0x%x):\r\n", size);
            for (uint32_t i = 0; i < size; i++)
            {
              (void)printf("%x ", output[i]);
            }
            (void)printf("\r\n");
          }
          else
          {
            (void)printf("\nTEST FAILED : %d \r\n", (int)psa_status);
          }
          break;
#ifdef TFM_CRYPTO_TEST_ALG_GCM
        case '2' :
          /* Display PSA API called in the test GCM */
          DISPLAY_AEAD();
          /* Test AES GCM with key test of 128 bits */
          psa_aead_test(PSA_KEY_TYPE_AES, PSA_ALG_GCM,
                        test_key_128, BIT_SIZE_TEST_KEY, &ret);
          (void)printf("\r\n%s\r\n", ret.info_msg);
          break;
#endif /* GCM */

#ifdef TFM_CRYPTO_TEST_ALG_CBC
        case '3' :
          /* Display PSA API called in the test CBC */
          (void)printf("\nPSA API tested : \r\n\n");
          (void)printf("psa_cipher_operation_init() \r\n");
          (void)printf("psa_key_attributes_init() \r\n");
          (void)printf("psa_set_key_usage_flags() \r\n");
          (void)printf("psa_set_key_algorithm() \r\n");
          (void)printf("psa_set_key_type() \r\n");
          (void)printf("psa_set_key_lifetime() \r\n");
          (void)printf("psa_import_key() \r\n");
          (void)printf("psa_get_key_attributes() \r\n");
          (void)printf("psa_get_key_bits() \r\n");
          (void)printf("psa_get_key_type() \r\n");
          (void)printf("psa_reset_key_attributes() \r\n");
          (void)printf("psa_cipher_encrypt() \r\n");
          (void)printf("psa_cipher_decrypt() \r\n");
          (void)printf("psa_cipher_encrypt_setup() \r\n");
          (void)printf("psa_cipher_set_iv() \r\n");
          (void)printf("psa_cipher_update() \r\n");
          (void)printf("psa_cipher_finish() \r\n");
          (void)printf("psa_cipher_decrypt_setup() \r\n");
          /* Test AES CBC with key test of 128 bits */
          psa_cipher_test(PSA_KEY_TYPE_AES, PSA_ALG_CBC_NO_PADDING,
                          test_key_128, BIT_SIZE_TEST_KEY, &ret);
          (void)printf("\r\n%s\r\n", ret.info_msg);
          break;
#endif /* CBC */

#ifdef TFM_CRYPTO_TEST_ALG_CCM
        case '4' :
          /* Display PSA API called in the test CCM */
          DISPLAY_AEAD();
          /* Test AES CCM with key test of 128 bits */
          psa_aead_test(PSA_KEY_TYPE_AES, PSA_ALG_CCM,
                        test_key_128, BIT_SIZE_TEST_KEY, &ret);
          (void)printf("\r\n%s\r\n", ret.info_msg);
          break;
#endif /* CCM */

        case '5' :
          /* Test SHA 224 */
          (void)printf("\nPSA API tested : \r\n\n");
          (void)printf("psa_hash_operation_init() \r\n");
          (void)printf("psa_hash_setup() \r\n");
          (void)printf("psa_hash_update() \r\n");
          (void)printf("psa_hash_verify() \r\n");
          (void)printf("psa_hash_compare() \r\n");
          psa_hash_test(PSA_ALG_SHA_224, &ret);
          (void)printf("\r\n%s\r\n", ret.info_msg);
          break;

        case '6' :
          /* Test SHA 256 */
          (void)printf("\nPSA API tested : \r\n\n");
          (void)printf("psa_hash_operation_init() \r\n");
          (void)printf("psa_hash_setup() \r\n");
          (void)printf("psa_hash_update() \r\n");
          (void)printf("psa_hash_verify() \r\n");
          (void)printf("psa_hash_compare() \r\n");
          psa_hash_test(PSA_ALG_SHA_256, &ret);
          (void)printf("\r\n%s\r\n", ret.info_msg);
          break;

        case '7' :
          /* Test RSA 2048 with SHA 256 algorithm */
          (void)printf("\nPSA API tested : \r\n\n");
          (void)printf("psa_key_attributes_init() \r\n");
          (void)printf("psa_set_key_usage_flags() \r\n");
          (void)printf("psa_set_key_algorithm() \r\n");
          (void)printf("psa_set_key_type() \r\n");
          (void)printf("psa_import_key() \r\n");
          (void)printf("psa_asymmetric_encrypt() \r\n");
          (void)printf("psa_asymmetric_decrypt() \r\n");
          (void)printf("psa_destroy_key() \r\n");
          psa_asymmetric_encryption_test(PSA_ALG_RSA_OAEP(PSA_ALG_SHA_256), &ret, 2048);
          (void)printf("\r\n%s\r\n", ret.info_msg);
          break;

        case 'X' :
        case 'x' :
          /* Exit crypto menu */
          exit = 1U;
          break;

        default:
          (void)printf("Invalid Number !\r\n");
          break;
      }

      if (exit == 0U)
      {
        /* Print Main Menu message */
        FW_APP_CRYPTO_PrintMenu();
      }
    }
  }
}

static void DISPLAY_AEAD(void)
{
  (void)printf("\nPSA API tested : \r\n\n");
  (void)printf("psa_aead_operation_init() \r\n");
  (void)printf("psa_key_attributes_init() \r\n");
  (void)printf("psa_set_key_usage_flags() \r\n");
  (void)printf("psa_set_key_algorithm() \r\n");
  (void)printf("psa_set_key_type() \r\n");
  (void)printf("psa_import_key() \r\n");
  (void)printf("psa_get_key_attributes() \r\n");
  (void)printf("psa_get_key_bits() \r\n");
  (void)printf("psa_get_key_type() \r\n");
  (void)printf("psa_reset_key_attributes() \r\n");
  (void)printf("psa_aead_encrypt() \r\n");
  (void)printf("psa_aead_decrypt() \r\n");
}
